exception: add special require-initialized helper
Like require-not-null but for non pointer object - e.g. optional.
Because it semantically incorrect to throw nullptr exception for them.