exception: fix require-not-null compatibility with explicit bool operator
Remove not needed conversion-to-bool check because
it duplicate behavior of if() statement.